language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 500
    branch_strategy: balanced
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
policies:
  - name: AugmentedMemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: FormPolicy
  - name: MappingPolicy