language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
  branch_strategy: balanced
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
policies:
- name: AugmentedMemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: FormPolicy
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.7
  core_threshold: 0.7
  fallback_action_name: action_default_fallback
